#cloud-config
hostname: ${HOSTNAME}
users:
  - default
  - name: ${USERNAME}
    groups: [canarybit]
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    ssh_authorized_keys:
      - ${SSH_PUBKEY}

timezone: UTC

package_update: true
package_upgrade: true
package_reboot_if_required: false
packages:
  - libtss2-dev
  - jq

write_files:
  # Custom policu for the current cVM instance (optional)
  - path: /etc/canarybit/custom-policy.rego
    defer: true
    permissions: '0600'
    content: |
      ${CUSTOM_POLICY}

  # Configure cbclient as a System service
  - path: /etc/systemd/system/cbclient.service
    defer: true
    permissions: '0600'
    content: |
      [Unit]
      Description=CanaryBit Remote Attestation
      
      [Service]
      EnvironmentFile=/home/tower/tokens
      Environment="CBCLIENT_LOG_LEVEL=info"
      Environment="CBCLIENT_ENVIRONMENTS=${ENVIRONMENTS}"
      Environment="CBCLIENT_INSPECTOR_URL=${CBINSPECTOR_URL}"
      Environment="CBCLIENT_ANNOTATIONS=${CBCLIENT_ANNOTATIONS}"
      Type=oneshot
      ExecStart=/bin/bash -c '/usr/local/bin/cbclient attestation --token $$(cb login inspector) --key /home/${USERNAME}/signing-key.pem ${CUSTOM_POLICY_OPT}'

  # Set a frequency for cbclient.service
  - path: /etc/systemd/system/cbclient.timer
    defer: true
    permissions: '0600'
    content: |
      [Unit]
      Description=CanaryBit Remote Attestation Timer
      
      [Timer]
      OnCalendar=${FREQUENCY}
      Persistent=true
      
      [Install]
      WantedBy=timers.target

  # Initialize the cbclient systemd service
  - path: /etc/canarybit/launch-cbclient
    defer: true
    permissions: '0755'
    content: |
      #!/bin/bash

      cat /home/tower/tokens >> /etc/environment

      set -a
      source /etc/environment
      set +a
      
      # Download the CanaryBit CLI (cb) into /usr/local/bin
      curl -fsSL https://canarybit-public-binaries.s3.eu-west-1.amazonaws.com/cb-cli/${CBCLI_V}/cb-x86_64-unknown-linux-gnu -o cb; chmod +x cb; mv cb /usr/local/bin/cb
            
      # Download the CanaryBit Inspector agent (cbclient) into /usr/local/bin
      cb download cbclient ${CBCLIENT_V}/cbclient; chmod +x cbclient; mv cbclient /usr/local/bin/cbclient

      cb login inspector
      # Start cbclient as System service once and then a defined frequency
      systemctl start cbclient.service
      systemctl enable --now cbclient.timer

final_message: |
  ==========   CANARYBIT TOWER SETUP COMPLETED IN $UPTIME secs    ==========
  The security and privacy of this environment is verified by CanaryBit Remote Attestation service:
  ${CBINSPECTOR_URL}
